config/routes.rb
Rails.application.routes.draw do
  resources :videos
  #root "videos#index"
  # root "countries#index"
  # resources :countries
  root "users#index"
  resources :users
  #get "delete_user", to: "users#delete_user"
  get "user_delete", to: "users#user_delete"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/country.rb
class Country < ApplicationRecord
    def self.import(file)
        CSV.foreach(file.path, headers: true) do |row|
            company_hash = Country.new
            company_hash.name = row[0]
            company_hash.code = row[1]
            company_hash.timezone = row[2]
			company_hash.save
        end
    end
end

app/models/user.rb
class User < ApplicationRecord 
	has_one_attached :clip

	def self.import(file)
		if file.content_type.in?(%w(application/vnd.ms-excel text/csv application/vnd.openxmlformats-officedocument.spreadsheetml.sheet))
			CSV.foreach(file.path, headers: true) do |row|
	            company_hash = User.new
				company_hash.date = row[0]
	            company_hash.timezone = row[1] 
	            company_hash.name = row[2]
	            company_hash.payment_type = row[3]
	            company_hash.status = row[4]
	            company_hash.currency = row[5]
	            company_hash.gross = row[6]
	            company_hash.fee = row[7]
	            company_hash.net = row[8]
	            company_hash.from_email = row[9]
	            company_hash.to_email = row[10]
	            company_hash.transaction_id = row[11]
	            company_hash.item_id = row[12]
	            company_hash.frequency = row[13]
				company_hash.save
            end
		end
    end
	after_create :send_mail
	def send_mail
        NotificationMailer.send_signup_email(self).deliver_now
    end
end









# var allowedExtension = ["csv", "xls"];
# $.each(inputFile.files, function() {
#     extName = this.name.split('.').pop();
#     if ($.inArray(extName, allowedExtension) == -1) {extError=true;};
#   })
 # private

   #def avatar_size_validation
 #   errors[:avatar] << "Must be a csv or a xls file" 
 #    if avatar.type == '.csv'
 #    	puts "valid"
 #    elsif avtar.type == '.xls' 
 #    	puts 'valid'
 #    elsif avtar.type == '.xlsx '
 #    	puts 'valid'
 #    else
 #    	puts 'invalid'
 # #    end
 #   end


 #  def extension_white_list
 #    %w(csv xls xlsx)
 #  end

 #  private

 #  def correct_document_mime_type
 #    if file.attached? && !file.content_type.in?(%w(application/csv application/xls))
 #       errors.add(:document, "Must be a csv or a xls file")
 #    end
 #  end

# def self.import(file)
  #        spreadsheet = open_spreadsheet(file)
 #        header = spreadsheet.row(1)
 #        (2..spreadsheet.last_row).each do |i|
 #          row = Hash[[header, spreadsheet.row(i)].transpose]
 #          user = find_by_id(row["id"]) || new
 #          user.attributes = row.to_hash.slice(*attr_accessor)
 #          user.save!
 #        end
 #    end
      
  #   def self.import(file)
  #       case File.extname(file.original_filename)
  #       when ".csv" then CSV.new(file.path, nil, :ignore)
		# when ".xls" then Excel.new(file.path, nil, :ignore)
		# when ".xlsx" then Roo::Excelx.new(file.path, nil, :ignore)
  #       else raise "Unknown file type: #{file.original_filename}"
  #       end
  #   end















	

app/models/video.rb
class Video < ApplicationRecord
	has_one_attached :clip
	has_one_attached :thumbnail
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController

  def new
    @country = Country.new
  end

  def index
    @countries = Country.all 
    @country =   Country.new 
  end


  def create
    Country.import(params[:country][:file])
    redirect_to countries_path 
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def index
    @users = User.all 
    @user  = User.new 
  end

  def create
    #debugger
    @user = User.new(clip:params[:user][:clip])

    #@user = User.new (video_params)
    @user.save
	  if User.import(params[:user][:file])
      redirect_to users_path,  notice:  "Imported users successfully."
    else
   		redirect_to users_path, notice: "file type must be csv or xls or xlsx"
   	end
  end

  # def destroy
  #  debugger 
  #  @user = User.find_by(params[:data])
  #  @user.destroy
  #  redirect_to root_path
  #  respond_to :js 
  # end

  # def delete_user
  #  @user = User.find_by(params[:data])
  #  @user.destroy
  #  redirect_to root_path
  #  respond_to :js 
  # end

  def user_delete
    #byebug
    @user = User.find_by(params[:data])
    @user.destroy
    redirect_to root_path
  end

  # private
  # def video_params
  #     params.require(:user).permit(:clip)
  # end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: %i[ show edit update destroy ]

  # GET /videos or /videos.json
  def index
    @videos = Video.all
  end

  # GET /videos/1 or /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos or /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: "Video was successfully created." }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1 or /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: "Video was successfully updated." }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1 or /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: "Video was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def video_params
      params.require(:video).permit(:title, :description, :clip, :thumbnail)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contries_helper.rb
module ContriesHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/contries/index.html.erb
<h1>Contries#index</h1>
<p>Find me in app/views/contries/index.html.erb</p>

app/views/contries/new.html.erb
<%= form_for @country, url: countries_path do |f| %>
   <div class="form-group">
      <%= f.label :file, "Upload CSV File" %>
      <%= f.file_field :file, class: 'form-control-file', required: true %>
   </div>
   <%= f.button :submit, "Upload CSV", class: 'btn btn-primary' %>
<% end %>

app/views/countries/index.html.erb
<br><br>
<%= form_for @country, url: countries_path do |f| %>
    <%= f.label :file, "Upload CSV or XLS File" %><br><br>
    <%= f.file_field :file, required: true %>
    <%= f.submit %>
<% end %><br>

<table>
	<thead>
		<tr>
			<th>Name</th>
			<th>Code</th>
			<th>TimeZone</th>
		</tr>
	</thead>
	<tbody>
		<% @countries.each do |country| %>
			<tr>
				<td><%= country.name %></td>
				<td><%= country.code %></td>
				<td><%= country.timezone %></td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/countries/new.html.erb
<%#= form_for @country, url: countries_path do |f| %>
   <div class="form-group">
      <%#= f.label :file, "Upload CSV File" %>
      <%#= f.file_field :file, class: 'form-control-file', required: true %>
   </div>
   <%#= f.button :submit, "Upload CSV" %>
<%# end %>
<br><br>
<%= form_tag countries_path, multipart: true do %>
        <%= file_field_tag :"country[:file]" %>
        <%= submit_tag "Import" %>
<% end %>	

app/views/layouts/application.html.erb
<html>
  <head>
    <title>Imp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_table.html.erb
<!-- <div style="width: 200px; height: 200px;">
    <%#= video_tag(url_for(@user.clip),style: 'width:100%; height: auto', controls:'')%>
</div>

 -->
<table style="margin-top:20px;width:10%;font-family: serif" class="table table-striped table-bordered table-hover ">
    <thead class="thead-dark">
        <!--  <tr style="background-color: #444;color:#fff">-->
        <tr>
            <th>Date</th>
            <th>Timezone</th>
            <th>Name</th>
            <th>Type</th>
            <th>Status</th>
            <th>Currency</th>
            <th>Gross</th>
            <th>Fee</th>
            <th>Net</th>
            <th>From_email</th>
            <th>To_email</th>
            <th>Transaction_id</th>
            <th>Item_id</th>
            <th>Frequency</th>
            <th>VIDEO</th>
            <th>Delete</td>
        </tr>
    </thead>
    <tbody>
        <% @users.each do |user| %>
        	<tr style="background:#444;color:#fff;font-family: serif">
                <td><%= user.date %></td>
				<td><%= user.timezone %></td>
				<td><%= user.name %></td>
				<td><%= user.payment_type %></td>
				<td><%= user.status %></td>
				<td><%= user.currency %></td>
				<td><%= user.gross %></td>
				<td><%= user.fee %></td>
				<td><%= user.net %></td>
				<td><%= user.from_email %></td>
				<td><%= user.to_email %></td>
				<td><%= user.transaction_id %></td>
				<td><%= user.item_id %></td>
				<td><%= user.frequency%></td>
                <td><%#= video_tag(url_for(user.clip),controls:'', style: 'width:5%; height:auto')%> </td>
                <td><button  type="button" value="<%= user.id%>" class = "aaa btn btn-danger">Destroy</button></td>
			</tr>    
        <% end%>
    </tbody>
</table>
<script type="text/javascript">
    $( document ).ready(function() {
        $(".aaa").on("click",function(){
            Swal.fire({
                title: 'Are you sure?',
                input: 'text',
                inputPlaceholder: 'ENTER DELETE',
                text:  "You won't be able to revert this!",
                icon:  'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, Delete it!'
                }).then((result) => {
                    if (result.isConfirmed){
                     Swal.fire(
                        'Deleted!',
                        'Your Record has been deleted.',
                        'success'
                        )
                    $.ajax({
                        url: "/user_delete",
                        type: "GET",
                        dataType: "script",
                        data: {data: $(this).attr('value')},
                        success: function(data){
                            location.reload();
                        }
                        
                    })
                }
            })
        });

});
</script>

app/views/users/index.html.erb
<!-- <div 
class="container"
style="margin:-100px 100px 0 0;">
 -->
<h4 
style="text-align: center; color: red"><%= flash[:notice]%>	
</h4>
<!-- 
<div 
style="margin-top:100px;width:130%;background:#444;padding:30px;border-radius:20px;"
> -->
<%#= form_for @user, url: users_path do |f| %>
<%= form_for User.new, :as => :user, :html => {:multipart => true} do |f| %>
<!-- 
<div 
	style="background:#fff;color:#000;width:100%;margin-top:20px;border-radius:0 10px 20px 10px;padding:7px;" >
	
</div> -->
	<%= f.label :file, "Upload CSV or XLS File" %>
    <%= f.file_field :file, required: true %>	<br>

<!-- 
<div 
	style="background:#fff;color:#000;width:100%;margin-top:20px;border-radius:0 10px 20px 10px;padding:7px;
	" class="field">
</div> -->
    	<%= f.label :clip %>
    	<%= f.file_field :clip %>
    

<h4 
    style="margin-top:20px;"
    id="p1"><%= f.submit class: "btn btn-primary btn-lg"%>		
</h4>

<% end %>

</div>
</div>
<%= render 'table' %>	

app/views/users/user_delete.js.erb
// $( document ).ready(function() {
//     $(".aaa").on("click",function() {
//         Swal.fire({
//                     title: 'Are you sure?',
//                     input: 'text',
//                     inputPlaceholder: 'ENTER DELETE',
//                     text:  "You won't be able to revert this!",
//                     icon:  'warning',
//                     showCancelButton: true,
//                     confirmButtonColor: '#3085d6',
//                     cancelButtonColor: '#d33',
//                     confirmButtonText: 'Yes, Delete it!'
//                   }).then((result) => {
//                   if (result.isConfirmed) {
//                      Swal.fire(
//                         'Deleted!',
//                         'Your Record has been deleted.',
//                         'success'
//                         )
//                     $.ajax({
//                         url: "/delete_user",
//                         type: "GET",
//                         dataType: "script",
//                         data: {data: $(this).attr('value')}
//                     })
//                 }
//             })
//         });
// });
// locarion.reload!
// location.reload(true);
// $.ajax({ 
//     <your deleting code>
//     success: function() {
//         window.location.reload();
//     })
// });
//location.reload()
//object.reload(forcedReload);

app/views/videos/_form.html.erb
<%= form_with(model: video) do |form| %>
  <% if video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
        <% video.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%#= form.label :title %>
    <%#= form.text_field :title %>
  </div>

  <div class="field">
    <%#= form.label :description %>
    <%#= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :clip %>
    <%= form.file_field :clip %>
  </div>

  <div class="field">
    <%#= form.label :thumbnail %>
    <%#= form.file_field :thumbnail %>
  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/videos/edit.html.erb
<h1>Editing Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Videos</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><%= video.title %></td>
        <td><%= video.description %></td>
        <td><%= video_tag(url_for(video.clip),controls:'', style: 'width:35%; height:auto')%> </td>
        <td><%#= image_tag((video.thumbnail),controls:'', style: 'width:35%; height:auto')%> </td>
        <td><%#= image_tag((image.clip),controls:'', style: 'width:40%; height:auto')%> </td>
        <td><%= link_to 'Show', video %></td>
        <td><%= link_to 'Edit', edit_video_path(video) %></td>
        <td><%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Video', new_video_path %>

app/views/videos/new.html.erb
<h1>New Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Back', videos_path %>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<div style="width: 200px; height: 200px;">
	<%= video_tag(url_for(@video.clip),style: 'width:100%; height: auto', controls:'')%>
</div>

<p>
  <strong>Title:</strong>
  <%= @video.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @video.description %>
</p>
<!--  <div style="width: 400px; height: 400px">
</div>-->
	<%#= image_tag(@video.thumbnail) %>


<%= link_to 'Edit', edit_video_path(@video) %> |
<%= link_to 'Back', videos_path %>